name: Prettier

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version: "lts/*"
          cache: "yarn"
      - run: yarn install --frozen-lockfile --no-progress
      - run: yarn run prettier:check
